In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

data = pd.read_csv('Student_Performance.csv')
#print(data['Performance_Index'])
y = data['Performance_Index']
X = data.drop(['Performance_Index'],axis=1)
#print(X)

In [6]:
# 使用最小二乘法估计线性模型
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X,y)
lin_reg.intercept_,lin_reg.coef_

(-34.0755880919136,
 array([2.85298205, 1.01843419, 0.61289758, 0.48055975, 0.19380214]))

In [11]:
# 使用梯度下降法估计线性模型
from sklearn.linear_model import SGDRegressor
sgd_reg = SGDRegressor()
sgd_reg.fit(X,y)
sgd_reg.intercept_,sgd_reg.coef_

(array([-34.74580702]),
 array([2.85413066, 1.00676659, 0.61645623, 0.56539037, 0.27609414]))

In [12]:
# 使用岭回归估计线性模型
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=1,solver='cholesky')
ridge_reg.fit(X,y)
ridge_reg.intercept_,ridge_reg.coef_

(-34.07510675292848,
 array([2.85293969, 1.01843385, 0.61265208, 0.48054147, 0.19380107]))

In [13]:
# 使用Lasso回归估计线性模型
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.1)
lasso_reg.fit(X,y)
lasso_reg.intercept_,lasso_reg.coef_

(-33.4947819888976,
 array([2.83858887, 1.01820802, 0.21107349, 0.44314152, 0.18288213]))

In [14]:
# 使用弹性网络估计线性模型
from sklearn.linear_model import ElasticNet
elastic_net = ElasticNet(alpha=0.1,l1_ratio=0.5)
elastic_net.fit(X,y)
elastic_net.intercept_,elastic_net.coef_

(-33.57623974206396,
 array([2.82477209, 1.01813521, 0.34320371, 0.45354796, 0.18771742]))

In [16]:
# 使用极大似然估计估计线性模型
from sklearn.linear_model import BayesianRidge
bayes_reg = BayesianRidge()
bayes_reg.fit(X,y)
bayes_reg.intercept_,bayes_reg.coef_

(-34.07457046567467,
 array([2.85289247, 1.01843346, 0.61237872, 0.48052109, 0.19379988]))

In [30]:
# 使用随机森林估计线性模型
from sklearn.ensemble import RandomForestRegressor
forest_reg = RandomForestRegressor()
re = forest_reg.fit(X,y)
print(re.score(X,y))

0.9974230318932085


In [31]:
# 使用支持向量机估计线性模型
from sklearn.svm import SVR
svm_reg = SVR(kernel='linear')
svm_reg.fit(X,y)
svm_reg.intercept_,svm_reg.coef_

(array([-34.03098273]),
 array([[2.85574556, 1.01795479, 0.63881158, 0.4746276 , 0.19005092]]))

In [32]:
# 使用最大后验概率估计线性模型
from sklearn.linear_model import ARDRegression
ard_reg = ARDRegression()
ard_reg.fit(X,y)
ard_reg.intercept_,ard_reg.coef_

(-34.07092158130558,
 array([2.85296751, 1.01843398, 0.61018092, 0.48024229, 0.19354867]))